### ISSUE TITLE
[요청] 페이지 뒤로가기 개선사항

### ISSUE THREAD

**Issue by klmhyeonwoo** [brgndyy/maeil-mail#49]
안녕하세요, 좋은 프로덕트 정말 정말 감사합니다,
항상 출근 길에 잘 사용하고 있습니다!

서비스를 이용하면서 이런 개선 사항이 있으면 좋겠다는 생각이 들어서 이렇게 이슈 템플릿으로 제보를 드립니다!
서비스 메인 기능에 대한 랜딩 페이지로 접근을 하게 되면 백엔드 · 프론트엔드와 같이 분류를 설정할 수 있는데,
세부 기술에 대한 내용을 확인하고 뒤로가기를 하면 상태가 초기화되어서 분류를 계속 지정을 해줘야하더라구요!
이 부분이 개선이 되면 더 사용하기 편할 것 같아 이렇게 제보드립니다 :-)

**Comment by brgndyy** [comment]
현우님 먼저 매일메일 이용해주셔서 정말 감사하다는 말씀드리고 싶습니다.

말씀 주신 부분 얼른 반영하여 업데이트 하도록 하겠습니다.

귀한 피드백 정말 감사드려요! 🙇
